spring:
  redis:
    # redis库   0->342  1->453  2->800
    database: 2
    host: 172.18.18.77
    port: 30379
    password: Red1s@9736
    timeout: 50000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
#  redis:
#    # 使用的数据库索引，默认是0
#    database: 0
#    # Redis服务器地址
#    host: 127.0.0.1
#    # Redis服务器端口号
#    port: 6379
#    # 设置密码
#    password:
#    # 连接超时时间
#    timeout: 1800000
#    lettuce:
#      pool:
#        # 最大阻塞等待时间，负数表示没有限制
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 5
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中最大连接数，负数表示没有限制
#        max-active: 20

server:
  port: 9999
